version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: simplerest
    expose:
    - "3306"
    ports:
    - 3306:3306
    volumes:
    - ./mysql_data:/var/lib/mysql  
    
